# If something shows up in deploy_staging or deploy_production
# we will do the lint check and deploy. 
# as of 11/22/2021 we only have deploy_staging working in practice

name: deploy

on:
  push:
    branches:
      - deploy_staging
      - deploy_production 
  pull_request:
    branches: 
      - deploy_staging
      - deploy_production 
 # workflow_dispatch:

# The deployment job is Inspired by https://www.twilio.com/blog/build-test-deploy-laravel-application-github-actions
# and https://laravel-news.com/push-deploy-with-github-actions 


jobs:
  phplinter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # PHP Linter (https://github.com/marketplace/actions/check-php-syntax-errors)
    - name: Linter
      uses: overtrue/phplint@8.0
      with:
        path: .
        options: --exclude=*.log
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd twc-webapp
            php artisan down --render dfm
            git checkout -f
            git pull
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
            cp ${{ secrets.PATH_TO_ENV_FILE }} /home/twc/twc-webapp/.env
            php artisan optimize 
            php artisan up
