name: PHP Composer and Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    # PHP Linter (https://github.com/marketplace/actions/check-php-syntax-errors)
  
    - name: Linter
      uses: overtrue/phplint@8.0
      with:
        path: .
        options: --exclude=*.log
    # May want to use Github's super linter (https://github.com/github/super-linter)
    - name: Super-Linter
      uses: github/super-linter@v4.8.1
      env:
      # Check the readme, this means only new or just checked in files will be linted, not EVERYTHING, that should make things run a lot faster than phplinter. 
        VALIDATE_ALL_CODEBASE: false         
        DEFAULT_BRANCH: main
        
      

      

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
